// Enchanted Forest
const enchantedForest = [
  {
    id: 1,
    name: "Fairy Flower Bulb",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Flower",
    magimins: {
      a: 4,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 14,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 2,
    name: "Impstool Mushroom",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Fungus",
    magimins: {
      a: 0,
      b: 4,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 17,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 3,
    name: "Rotfly Larva",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Bug",
    magimins: {
      a: 0,
      b: 0,
      c: 4,
      d: 0,
      e: 0,
    },
    basePrice: 10,
    quinnQuantity: 10,
    traits: {
      taste: 1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 4,
    name: "Feyberry",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Fruit",
    magimins: {
      a: 6,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 4,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 5,
    name: "Mandrake Root",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Plant",
    magimins: {
      a: 0,
      b: 6,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 6,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 6,
    name: "Sack of Slime",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Slime",
    magimins: {
      a: 0,
      b: 0,
      c: 6,
      d: 0,
      e: 0,
    },
    basePrice: 7,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 7,
    name: "River Calamari",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Fish",
    magimins: {
      a: 8,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 5,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: -1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 8,
    name: "Serpent's Slippery Tongue",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Flesh",
    magimins: {
      a: 0,
      b: 8,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 6,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: -1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 9,
    name: "Unicorn Horn",
    location: "Enchanted Forest",
    rarity: 1,
    type: "Bone",
    magimins: {
      a: 0,
      b: 0,
      c: 8,
      d: 0,
      e: 0,
    },
    basePrice: 6,
    quinnQuantity: 10,
    traits: {
      taste: -1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 10,
    name: "River-Pixie's Shell",
    location: "Enchanted Forest",
    rarity: 2,
    type: "Mineral",
    magimins: {
      a: 4,
      b: 4,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 11,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 11,
    name: "Kappa Pheromones",
    location: "Enchanted Forest",
    rarity: 2,
    type: "Essence",
    magimins: {
      a: 4,
      b: 0,
      c: 4,
      d: 0,
      e: 0,
    },
    basePrice: 13,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 12,
    name: "Pixiedust Diamond",
    location: "Enchanted Forest",
    rarity: 2,
    type: "Gem",
    magimins: {
      a: 0,
      b: 4,
      c: 4,
      d: 0,
      e: 0,
    },
    basePrice: 14,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 13,
    name: "Cubic Ooze",
    location: "Enchanted Forest",
    rarity: 3,
    type: "Slime",
    magimins: {
      a: 3,
      b: 3,
      c: 3,
      d: 0,
      e: 0,
    },
    basePrice: 16,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
];

const mushroomMire = [
  {
    id: 14,
    name: "Trollstool Mushroom",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Fungus",
    magimins: {
      a: 0,
      b: 12,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 20,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 15,
    name: "Murkwater Pearl",
    location: "Mushroom Mire",
    rarity: 2,
    type: "Gem",
    magimins: {
      a: 0,
      b: 0,
      c: 0,
      d: 12,
      e: 0,
    },
    basePrice: 27,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 1,
      sound: 0,
    },
  },
  {
    id: 16,
    name: "Bog Beet",
    location: "Mushroom Mire",
    rarity: 3,
    type: "Plant",
    magimins: {
      a: 0,
      b: 27,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 27,
    quinnQuantity: 2,
    traits: {
      taste: -1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 1,
    },
  },
  {
    id: 17,
    name: "Raven's Shadow",
    location: "Mushroom Mire",
    rarity: 3,
    type: "Essence",
    magimins: {
      a: 0,
      b: 10,
      c: 12,
      d: 18,
      e: 0,
    },
    basePrice: 52,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 18,
    name: "Wraith Orchid",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Flower",
    magimins: {
      a: 0,
      b: 0,
      c: 0,
      d: 12,
      e: 0,
    },
    basePrice: 19,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 19,
    name: "Puckberry",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Fruit",
    magimins: {
      a: 18,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 16,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 20,
    name: "Swamp Octopus",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Fish",
    magimins: {
      a: 24,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 18,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: -1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 21,
    name: "Crocodile Tooth",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Bone",
    magimins: {
      a: 6,
      b: 0,
      c: 12,
      d: 0,
      e: 0,
    },
    basePrice: 20,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 22,
    name: "Sack of Hive Slime",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Slime",
    magimins: {
      a: 6,
      b: 0,
      c: 18,
      d: 0,
      e: 0,
    },
    basePrice: 21,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 23,
    name: "Swamp Fish",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Fish",
    magimins: {
      a: 12,
      b: 0,
      c: 0,
      d: 6,
      e: 0,
    },
    basePrice: 18,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 24,
    name: "Warg Pheromones",
    location: "Mushroom Mire",
    rarity: 2,
    type: "Essence",
    magimins: {
      a: 12,
      b: 0,
      c: 12,
      d: 0,
      e: 0,
    },
    basePrice: 26,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 25,
    name: "Ghostlight Bloom",
    location: "Mushroom Mire",
    rarity: 2,
    type: "Flower",
    magimins: {
      a: 18,
      b: 0,
      c: 0,
      d: 6,
      e: 0,
    },
    basePrice: 28,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 26,
    name: "Moss Berries",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Fruit",
    magimins: {
      a: 0,
      b: 10,
      c: 0,
      d: 20,
      e: 0,
    },
    basePrice: 35,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 27,
    name: "Bubble Ooze",
    location: "Mushroom Mire",
    rarity: 4,
    type: "Slime",
    magimins: {
      a: 9,
      b: 9,
      c: 12,
      d: 12,
      e: 0,
    },
    basePrice: 60,
    quinnQuantity: 1,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 28,
    name: "Miasma Spore",
    location: "Mushroom Mire",
    rarity: 2,
    type: "Fungus",
    magimins: {
      a: 0,
      b: 18,
      c: 0,
      d: 6,
      e: 0,
    },
    basePrice: 30,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 29,
    name: "Mud Shrimp",
    location: "Mushroom Mire",
    rarity: 3,
    type: "Fish",
    magimins: {
      a: 6,
      b: 0,
      c: 12,
      d: 0,
      e: 0,
    },
    basePrice: 26,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 30,
    name: "Hydra Vertebra",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Bone",
    magimins: {
      a: 9,
      b: 9,
      c: 9,
      d: 0,
      e: 0,
    },
    basePrice: 35,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 31,
    name: "Qilin's Tri-Horn",
    location: "Mushroom Mire",
    rarity: 1,
    type: "Bone",
    magimins: {
      a: 0,
      b: 0,
      c: 24,
      d: 0,
      e: 0,
    },
    basePrice: 10,
    quinnQuantity: 10,
    traits: {
      taste: -1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
];

const boneWastes = [
  {
    id: 32,
    name: "Fairy Flower Bud",
    location: "Bone Wastes",
    rarity: 1,
    type: "Flower",
    magimins: {
      a: 12,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 23,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 33,
    name: "Leech Snail's Shell",
    location: "Bone Wastes",
    rarity: 2,
    type: "Mineral",
    magimins: {
      a: 12,
      b: 12,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 26,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 34,
    name: "Golem's-Eye Diamond",
    location: "Bone Wastes",
    rarity: 2,
    type: "Gem",
    magimins: {
      a: 0,
      b: 12,
      c: 12,
      d: 0,
      e: 0,
    },
    basePrice: 28,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 35,
    name: "Desert Metal",
    location: "Bone Wastes",
    rarity: 1,
    type: "Ore",
    magimins: {
      a: 0,
      b: 12,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 25,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 36,
    name: "Rotfly Cocoon",
    location: "Bone Wastes",
    rarity: 2,
    type: "Bug",
    magimins: {
      a: 0,
      b: 0,
      c: 12,
      d: 0,
      e: 0,
    },
    basePrice: 25,
    quinnQuantity: 4,
    traits: {
      taste: 1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 37,
    name: "Sphinx Flea",
    location: "Bone Wastes",
    rarity: 3,
    type: "Bug",
    magimins: {
      a: 12,
      b: 6,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 35,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 38,
    name: "Manwyrm Root",
    location: "Bone Wastes",
    rarity: 1,
    type: "Plant",
    magimins: {
      a: 0,
      b: 18,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 14,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 39,
    name: "Figment Pomme",
    location: "Bone Wastes",
    rarity: 2,
    type: "Fruit",
    magimins: {
      a: 0,
      b: 18,
      c: 6,
      d: 0,
      e: 0,
    },
    basePrice: 26,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 40,
    name: "Glass Ore",
    location: "Bone Wastes",
    rarity: 1,
    type: "Ore",
    magimins: {
      a: 0,
      b: 0,
      c: 0,
      d: 18,
      e: 0,
    },
    basePrice: 24,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 41,
    name: "Salamander's Fiery Tongue",
    location: "Bone Wastes",
    rarity: 1,
    type: "Flesh",
    magimins: {
      a: 0,
      b: 24,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 22,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: -1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 42,
    name: "Frog Leg",
    location: "Bone Wastes",
    rarity: 4,
    type: "Flesh",
    magimins: {
      a: 0,
      b: 0,
      c: 24,
      d: 12,
      e: 0,
    },
    basePrice: 33,
    quinnQuantity: 1,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: -1,
      sound: 0,
    },
  },
  {
    id: 43,
    name: "Golemite",
    location: "Bone Wastes",
    rarity: 3,
    type: "Mineral",
    magimins: {
      a: 18,
      b: 12,
      c: 0,
      d: 10,
      e: 0,
    },
    basePrice: 38,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 44,
    name: "Horned Jelly",
    location: "Bone Wastes",
    rarity: 2,
    type: "Slime",
    magimins: {
      a: 18,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 20,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: -1,
      aroma: 0,
      visual: 1,
      sound: 0,
    },
  },
];

const stormPlains = [
  {
    id: 45,
    name: "Thunderbird's Molted Feather",
    location: "Storm Plains",
    rarity: 3,
    type: "Flesh",
    magimins: {
      a: 0,
      b: 0,
      c: 30,
      d: 0,
      e: 10,
    },
    basePrice: 60,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 46,
    name: "Giantstool Mushroom",
    location: "Storm Plains",
    rarity: 1,
    type: "Fungus",
    magimins: {
      a: 0,
      b: 20,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 40,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 47,
    name: "Fire Flower",
    location: "Storm Plains",
    rarity: 3,
    type: "Flower",
    magimins: {
      a: 40,
      b: 0,
      c: 0,
      d: 20,
      e: 0,
    },
    basePrice: 55,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: -1,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 48,
    name: "Copper Dollop",
    location: "Storm Plains",
    rarity: 3,
    type: "Slime",
    magimins: {
      a: 15,
      b: 15,
      c: 15,
      d: 15,
      e: 0,
    },
    basePrice: 95,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 49,
    name: "Static Spiderling",
    location: "Storm Plains",
    rarity: 3,
    type: "Bug",
    magimins: {
      a: 0,
      b: 0,
      c: 0,
      d: 0,
      e: 30,
    },
    basePrice: 50,
    quinnQuantity: 2,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: -1,
      sound: 1,
    },
  },
  {
    id: 50,
    name: "Slapping Turtle's Shell",
    location: "Storm Plains",
    rarity: 1,
    type: "Mineral",
    magimins: {
      a: 20,
      b: 20,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 46,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 51,
    name: "Antlered Jelly",
    location: "Storm Plains",
    rarity: 2,
    type: "Slime",
    magimins: {
      a: 30,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 28,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: -1,
      aroma: 0,
      visual: 1,
      sound: 0,
    },
  },
  {
    id: 52,
    name: "Fulgurite Ore",
    location: "Storm Plains",
    rarity: 2,
    type: "Ore",
    magimins: {
      a: 0,
      b: 0,
      c: 0,
      d: 30,
      e: 0,
    },
    basePrice: 40,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 53,
    name: "Raiju Droppings",
    location: "Storm Plains",
    rarity: 2,
    type: "Essence",
    magimins: {
      a: 0,
      b: 0,
      c: 30,
      d: 10,
      e: 0,
    },
    basePrice: 55,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 54,
    name: "Electrocution Eel",
    location: "Storm Plains",
    rarity: 2,
    type: "Fish",
    magimins: {
      a: 10,
      b: 10,
      c: 10,
      d: 0,
      e: 0,
    },
    basePrice: 45,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 1,
      sound: 0,
    },
  },
  {
    id: 55,
    name: "Bogeyberry",
    location: "Storm Plains",
    rarity: 1,
    type: "Fruit",
    magimins: {
      a: 30,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 30,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 56,
    name: "Spriggan Antler",
    location: "Storm Plains",
    rarity: 2,
    type: "Bone",
    magimins: {
      a: 0,
      b: 0,
      c: 40,
      d: 0,
      e: 0,
    },
    basePrice: 38,
    quinnQuantity: 4,
    traits: {
      taste: -1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 57,
    name: "Thunder Quartz",
    location: "Storm Plains",
    rarity: 2,
    type: "Gem",
    magimins: {
      a: 30,
      b: 10,
      c: 20,
      d: 0,
      e: 0,
    },
    basePrice: 72,
    quinnQuantity: 4,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
];

const oceanCoasts = [
  {
    id: 58,
    name: "Mandragon Root",
    location: "Ocean Coasts",
    rarity: 1,
    type: "Plant",
    magimins: {
      a: 30,
      b: 10,
      c: 20,
      d: 0,
      e: 0,
    },
    basePrice: 34,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 59,
    name: "Dwarf Kraken",
    location: "Ocean Coasts",
    rarity: 1,
    type: "Fish",
    magimins: {
      a: 40,
      b: 0,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 30,
    quinnQuantity: 10,
    traits: {
      taste: 0,
      sensation: -1,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 60,
    name: "Reef Radish",
    location: "Ocean Coasts",
    rarity: 3,
    type: "Plant",
    magimins: {
      a: 0,
      b: 30,
      c: 0,
      d: 0,
      e: 0,
    },
    basePrice: 32,
    quinnQuantity: 2,
    traits: {
      taste: -1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 1,
    },
  },
  {
    id: 61,
    name: "Rotfly Adult",
    location: "Ocean Coasts",
    rarity: 2,
    type: "Bug",
    magimins: {
      a: 0,
      b: 0,
      c: 20,
      d: 0,
      e: 0,
    },
    basePrice: 38,
    quinnQuantity: 4,
    traits: {
      taste: 1,
      sensation: 0,
      aroma: 0,
      visual: 0,
      sound: 0,
    },
  },
  {
    id: 62,
    name: "Saltwatermelon",
    location: "Ocean Coasts",
    rarity: 2,
    type: "Fruit",
    magimins: { a: 0, b: 0, c: 0, d: 40, e: 0 },
    basePrice: 44,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 0 },
  },
  {
    id: 63,
    name: "Selkie Lice",
    location: "Ocean Coasts",
    rarity: 3,
    type: "Bug",
    magimins: { a: 10, b: 20, c: 0, d: 0, e: 0 },
    basePrice: 50,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 64,
    name: "Nessie Pheromones",
    location: "Ocean Coasts",
    rarity: 1,
    type: "Essence",
    magimins: { a: 20, b: 0, c: 20, d: 0, e: 0 },
    basePrice: 50,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 65,
    name: "Jelly Blossom",
    location: "Ocean Coasts",
    rarity: 3,
    type: "Flower",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 30 },
    basePrice: 55,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 66,
    name: "Sea Salt",
    location: "Ocean Coasts",
    rarity: 2,
    type: "Mineral",
    magimins: { a: 30, b: 0, c: 0, d: 0, e: 10 },
    basePrice: 55,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 67,
    name: "Phantom Ponne",
    location: "Ocean Coasts",
    rarity: 4,
    type: "Fruit",
    magimins: { a: 0, b: 10, c: 30, d: 0, e: 0 },
    basePrice: 64,
    quinnQuantity: 1,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 68,
    name: "Abyssalite",
    location: "Ocean Coasts",
    rarity: 2,
    type: "Mineral",
    magimins: { a: 30, b: 20, c: 0, d: 0, e: 10 },
    basePrice: 79,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 69,
    name: "Malachite Ore",
    location: "Ocean Coasts",
    rarity: 3,
    type: "Ore",
    magimins: { a: 30, b: 10, c: 0, d: 0, e: 20 },
    basePrice: 93,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 70,
    name: "Squid Vine",
    location: "Ocean Coasts",
    rarity: 3,
    type: "Plant",
    magimins: { a: 20, b: 20, c: 15, d: 0, e: 15 },
    basePrice: 135,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
];

const shadowSteppe = [
  {
    id: 71,
    name: "Banshee's Bloody Tongue",
    location: "Shadow Steppe",
    rarity: 1,
    type: "Flesh",
    magimins: { a: 0, b: 40, c: 0, d: 0, e: 0 },
    basePrice: 32,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 72,
    name: "Fairy Flower Bloom",
    location: "Shadow Steppe",
    rarity: 1,
    type: "Flower",
    magimins: { a: 20, b: 0, c: 0, d: 0, e: 0 },
    basePrice: 35,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 73,
    name: "Hallucinatory Shroom",
    location: "Shadow Steppe",
    rarity: 3,
    type: "Fungus",
    magimins: { a: 0, b: 0, c: 30, d: 0, e: 0 },
    basePrice: 36,
    quinnQuantity: 2,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 74,
    name: "Sack of Composite Slime",
    location: "Shadow Steppe",
    rarity: 1,
    type: "Slime",
    magimins: { a: 0, b: 0, c: 30, d: 0, e: 0 },
    basePrice: 36,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 75,
    name: "Shadowveil Pearl",
    location: "Shadow Steppe",
    rarity: 2,
    type: "Gem",
    magimins: { a: 0, b: 0, c: 0, d: 20, e: 0 },
    basePrice: 38,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 76,
    name: "Cobweb Crayfish",
    location: "Shadow Steppe",
    rarity: 3,
    type: "Fish",
    magimins: { a: 10, b: 0, c: 20, d: 0, e: 0 },
    basePrice: 48,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 77,
    name: "Spider's-Bait Diamond",
    location: "Shadow Steppe",
    rarity: 2,
    type: "Gem",
    magimins: { a: 0, b: 20, c: 20, d: 0, e: 0 },
    basePrice: 50,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 78,
    name: "Barghast Canine",
    location: "Shadow Steppe",
    rarity: 3,
    type: "Bone",
    magimins: { a: 0, b: 30, c: 0, d: 0, e: 10 },
    basePrice: 55,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 79,
    name: "Photonic Spore",
    location: "Shadow Steppe",
    rarity: 4,
    type: "Fungus",
    magimins: { a: 0, b: 10, c: 0, d: 30, e: 0 },
    basePrice: 52,
    quinnQuantity: 1,
    traits: { taste: -1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 80,
    name: "Dropspider's Shadow",
    location: "Shadow Steppe",
    rarity: 3,
    type: "Essence",
    magimins: { a: 0, b: 0, c: 30, d: 20, e: 10 },
    basePrice: 90,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 81,
    name: "Mosquito Plant",
    location: "Shadow Steppe",
    rarity: 4,
    type: "Plant",
    magimins: { a: 10, b: 0, c: 20, d: 0, e: 30 },
    basePrice: 105,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 82,
    name: "Mote of Mana",
    location: "Shadow Steppe",
    rarity: NaN,
    type: "Mana",
    magimins: { a: 15, b: 15, c: 15, d: 15, e: 15 },
    basePrice: 130,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
];

const sulfuricFalls = [
  {
    id: 83,
    name: "Bramble-Rose",
    location: "Sulfuric Falls",
    rarity: 2,
    type: "Flower",
    magimins: { a: 16, b: 0, c: 0, d: 0, e: 0 },
    basePrice: 45,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 84,
    name: "Acid Rutabaga",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Plant",
    magimins: { a: 0, b: 48, c: 0, d: 0, e: 0 },
    basePrice: 54,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 85,
    name: "Rotfly Matriarch",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Bug",
    magimins: { a: 0, b: 0, c: 32, d: 0, e: 0 },
    basePrice: 65,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 86,
    name: "Weeping Metal Ore",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Ore",
    magimins: { a: 0, b: 32, c: 64, d: 0, e: 0 },
    basePrice: 66,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 87,
    name: "Rottermelon",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Fruit",
    magimins: { a: 0, b: 0, c: 0, d: 64, e: 0 },
    basePrice: 68,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 0 },
  },
  {
    id: 88,
    name: "Daydream Pomme",
    location: "Sulfuric Falls",
    rarity: 3,
    type: "Fruit",
    magimins: { a: 0, b: 24, c: 8, d: 0, e: 0 },
    basePrice: 75,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 1 },
  },
  {
    id: 89,
    name: "Scimitar Crab's Shell",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Mineral",
    magimins: { a: 32, b: 32, c: 0, d: 0, e: 0 },
    basePrice: 76,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 90,
    name: "Shelled Pudding",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Slime",
    magimins: { a: 32, b: 0, c: 0, d: 32, e: 0 },
    basePrice: 90,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 91,
    name: "Creeping Mildew",
    location: "Sulfuric Falls",
    rarity: 2,
    type: "Fungus",
    magimins: { a: 16, b: 0, c: 0, d: 0, e: 48 },
    basePrice: 92,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 92,
    name: "Hangman Eel",
    location: "Sulfuric Falls",
    rarity: 2,
    type: "Fish",
    magimins: { a: 24, b: 24, c: 24, d: 0, e: 0 },
    basePrice: 95,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 93,
    name: "Naga's Fang",
    location: "Sulfuric Falls",
    rarity: 1,
    type: "Bone",
    magimins: { a: 0, b: 48, c: 0, d: 0, e: 16 },
    basePrice: 98,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 94,
    name: "Lamia's Shed Scales",
    location: "Sulfuric Falls",
    rarity: 2,
    type: "Flesh",
    magimins: { a: 0, b: 0, c: 0, d: 48, e: 16 },
    basePrice: 110,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 95,
    name: "Bioplasm",
    location: "Sulfuric Falls",
    rarity: 3,
    type: "Essence",
    magimins: { a: 0, b: 48, c: 32, d: 16, e: 0 },
    basePrice: 125,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 1 },
  },
  {
    id: 96,
    name: "Acid Pitfall Plant",
    location: "Sulfuric Falls",
    rarity: 2,
    type: "Plant",
    magimins: { a: 16, b: 0, c: 40, d: 0, e: 40 },
    basePrice: 145,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 97,
    name: "Poison Quartz",
    location: "Sulfuric Falls",
    rarity: 3,
    type: "Gem",
    magimins: { a: 64, b: 48, c: 0, d: 32, e: 0 },
    basePrice: 185,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 98,
    name: "Charredonnay",
    location: "Sulfuric Falls",
    rarity: 3,
    type: "Fruit",
    magimins: { a: 48, b: 0, c: 48, d: 24, e: 24 },
    basePrice: 260,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
];

const iceCraggs = [
  {
    id: 99,
    name: "Silver Stag Antler",
    location: "Ice Craggs",
    rarity: 1,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 64, d: 0, e: 0 },
    basePrice: 72,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 100,
    name: "Celestial Ore",
    location: "Ice Craggs",
    rarity: 2,
    type: "Ore",
    magimins: { a: 0, b: 0, c: 16, d: 0, e: 0 },
    basePrice: 45,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 1, sound: 0 },
  },
  {
    id: 101,
    name: "Feathered Gelatin",
    location: "Ice Craggs",
    rarity: 2,
    type: "Slime",
    magimins: { a: 0, b: 0, c: 0, d: 48, e: 0 },
    basePrice: 62,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 102,
    name: "Rock salt",
    location: "Ice Craggs",
    rarity: 2,
    type: "Mineral",
    magimins: { a: 24, b: 0, c: 0, d: 0, e: 8 },
    basePrice: 68,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 103,
    name: "Courtier's Orchid",
    location: "Ice Craggs",
    rarity: 4,
    type: "Flower",
    magimins: { a: 8, b: 24, c: 24, d: 0, e: 0 },
    basePrice: 72,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 104,
    name: "Crag Crab",
    location: "Ice Craggs",
    rarity: 3,
    type: "Fish",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 32 },
    basePrice: 75,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 105,
    name: "Harpy's Heart of Stone",
    location: "Ice Craggs",
    rarity: 2,
    type: "Flesh",
    magimins: { a: 16, b: 0, c: 0, d: 32, e: 0 },
    basePrice: 76,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 106,
    name: "Sepulcher Widow",
    location: "Ice Craggs",
    rarity: 2,
    type: "Bug",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 48 },
    basePrice: 82,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 1 },
  },
  {
    id: 107,
    name: "Watchdog Daisy",
    location: "Ice Craggs",
    rarity: 1,
    type: "Flower",
    magimins: { a: 0, b: 16, c: 0, d: 48, e: 0 },
    basePrice: 83,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 108,
    name: "Griffin's-Whetstone Diamond",
    location: "Ice Craggs",
    rarity: 1,
    type: "Gem",
    magimins: { a: 0, b: 32, c: 32, d: 0, e: 0 },
    basePrice: 86,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 109,
    name: "Medusa Spore",
    location: "Ice Craggs",
    rarity: 1,
    type: "Fungus",
    magimins: { a: 0, b: 48, c: 0, d: 16, e: 0 },
    basePrice: 94,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 110,
    name: "Supernalite",
    location: "Ice Craggs",
    rarity: 3,
    type: "Mineral",
    magimins: { a: 48, b: 32, c: 0, d: 16, e: 0 },
    basePrice: 134,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 111,
    name: "Buoyant Blowfish",
    location: "Ice Craggs",
    rarity: 2,
    type: "Fish",
    magimins: { a: 96, b: 0, c: 48, d: 0, e: 0 },
    basePrice: 138,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: -1 },
  },
  {
    id: 112,
    name: "Avalanche Cricket",
    location: "Ice Craggs",
    rarity: 1,
    type: "Bug",
    magimins: { a: 24, b: 24, c: 32, d: 32, e: 0 },
    basePrice: 140,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: -1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 113,
    name: "Harpy's Snare",
    location: "Ice Craggs",
    rarity: 4,
    type: "Plant",
    magimins: { a: 24, b: 24, c: 24, d: 0, e: 24 },
    basePrice: 150,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 114,
    name: "Stalking Skeleton's Fibula",
    location: "Ice Craggs",
    rarity: 2,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 40, d: 40, e: 16 },
    basePrice: 150,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 115,
    name: "Ember of mana",
    location: "Ice Craggs",
    rarity: 4,
    type: "Mana",
    magimins: { a: 24, b: 24, c: 24, d: 24, e: 24 },
    basePrice: 165,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
];

const crystallineForest = [
  {
    id: 116,
    name: "Eye of Newt",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Flesh",
    magimins: { a: 0, b: 16, c: 0, d: 0, e: 0 },
    basePrice: 34,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 117,
    name: "Delirium Shroom",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Fungus",
    magimins: { a: 0, b: 0, c: 48, d: 0, e: 0 },
    basePrice: 63,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 118,
    name: "Djinn Blossom",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Flower",
    magimins: { a: 24, b: 0, c: 0, d: 8, e: 0 },
    basePrice: 68,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 119,
    name: "Ogre's Shadow",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Essence",
    magimins: { a: 32, b: 0, c: 32, d: 0, e: 0 },
    basePrice: 74,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 120,
    name: "Phoenix Tear",
    location: "Crystalline Forest",
    rarity: 4,
    type: "Essence",
    magimins: { a: 0, b: 24, c: 24, d: 8, e: 0 },
    basePrice: 82,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 121,
    name: "Owlbear Pheromones",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Essence",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 64 },
    basePrice: 90,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 122,
    name: "Daredevil Pepper",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Plant",
    magimins: { a: 0, b: 32, c: 0, d: 32, e: 0 },
    basePrice: 90,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 123,
    name: "Geode Citrus",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Fruit",
    magimins: { a: 0, b: 16, c: 0, d: 0, e: 48 },
    basePrice: 94,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 124,
    name: "Lazuli Ore",
    location: "Crystalline Forest",
    rarity: 3,
    type: "Ore",
    magimins: { a: 64, b: 48, c: 0, d: 0, e: 32 },
    basePrice: 174,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 125,
    name: "Shallow Grave Enoki",
    location: "Crystalline Forest",
    rarity: 3,
    type: "Fungus",
    magimins: { a: 32, b: 64, c: 64, d: 32, e: 0 },
    basePrice: 200,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: -1, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 126,
    name: "Chimera Waste",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Essence",
    magimins: { a: 0, b: 0, c: 64, d: 32, e: 0 },
    basePrice: 118,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 127,
    name: "Jeweled scarab",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Bug",
    magimins: { a: 0, b: 24, c: 24, d: 24, e: 0 },
    basePrice: 105,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 128,
    name: "Lustrous Pearl",
    location: "Crystalline Forest",
    rarity: 1,
    type: "Gem",
    magimins: { a: 0, b: 0, c: 0, d: 32, e: 0 },
    basePrice: 60,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 129,
    name: "Silver Dollop",
    location: "Crystalline Forest",
    rarity: 4,
    type: "Slime",
    magimins: { a: 24, b: 24, c: 24, d: 24, e: 0 },
    basePrice: 138,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 130,
    name: "Pegasus Mite",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Bug",
    magimins: { a: 96, b: 48, c: 0, d: 0, e: 0 },
    basePrice: 134,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 131,
    name: "Sequined Custard",
    location: "Crystalline Forest",
    rarity: 2,
    type: "Slime",
    magimins: { a: 0, b: 0, c: 32, d: 0, e: 16 },
    basePrice: 84,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
];

const arctic = [
  {
    id: 132,
    name: "Hoarite",
    location: "Arctic",
    rarity: 3,
    type: "Mineral",
    magimins: { a: 55, b: 55, c: 0, d: 22, e: 0 },
    basePrice: 167,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 133,
    name: "Orchid of the Ice Princess",
    location: "Arctic",
    rarity: 3,
    type: "Flower",
    magimins: { a: 11, b: 33, c: 0, d: 33, e: 0 },
    basePrice: 116,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 134,
    name: "Draugr's Tibia",
    location: "Arctic",
    rarity: 2,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 55, d: 55, e: 22 },
    basePrice: 184,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 135,
    name: "Snowflake Spore",
    location: "Arctic",
    rarity: 1,
    type: "Fungus",
    magimins: { a: 0, b: 66, c: 0, d: 22, e: 0 },
    basePrice: 108,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 136,
    name: "Hellhound Daisy",
    location: "Arctic",
    rarity: 2,
    type: "Flower",
    magimins: { a: 0, b: 22, c: 0, d: 66, e: 0 },
    basePrice: 125,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 137,
    name: "Yeti Antler",
    location: "Arctic",
    rarity: 1,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 88, d: 0, e: 0 },
    basePrice: 104,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 138,
    name: "Nether Ore",
    location: "Arctic",
    rarity: 3,
    type: "Ore",
    magimins: { a: 0, b: 0, c: 22, d: 0, e: 0 },
    basePrice: 51,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 1, sound: 0 },
  },
  {
    id: 139,
    name: "Winged Gelatin",
    location: "Arctic",
    rarity: 2,
    type: "Slime",
    magimins: { a: 0, b: 0, c: 0, d: 66, e: 0 },
    basePrice: 103,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 140,
    name: "Blackfrost Lobster",
    location: "Arctic",
    rarity: 2,
    type: "Fish",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 44 },
    basePrice: 104,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 141,
    name: "Jotunn's Frozen Heart",
    location: "Arctic",
    rarity: 2,
    type: "Flesh",
    magimins: { a: 22, b: 0, c: 0, d: 44, e: 0 },
    basePrice: 98,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 142,
    name: "Direwolf's-Breath Diamond",
    location: "Arctic",
    rarity: 1,
    type: "Gem",
    magimins: { a: 0, b: 44, c: 44, d: 0, e: 0 },
    basePrice: 118,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 143,
    name: "Diamond Salt",
    location: "Arctic",
    rarity: 2,
    type: "Mineral",
    magimins: { a: 33, b: 0, c: 0, d: 0, e: 11 },
    basePrice: 85,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 144,
    name: "Frost Hopper",
    location: "Arctic",
    rarity: 1,
    type: "Bug",
    magimins: { a: 33, b: 33, c: 44, d: 44, e: 0 },
    basePrice: 196,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: -1, aroma: 0, visual: 0, sound: 0 },
  },

  {
    id: 145,
    name: "Abominable Tarantula",
    location: "Arctic",
    rarity: 2,
    type: "Bug",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 66 },
    basePrice: 105,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 1 },
  },
  {
    id: 146,
    name: "Icicle Pufferfish",
    location: "Arctic",
    rarity: 2,
    type: "Fish",
    magimins: { a: 132, b: 0, c: 66, d: 0, e: 0 },
    basePrice: 210,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: -1 },
  },
  {
    id: 147,
    name: "Mana Conflagration",
    location: "Arctic",
    rarity: 4,
    type: "Mana",
    magimins: { a: 35, b: 45, c: 55, d: 65, e: 75 },
    basePrice: 316,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: -1, sound: 0 },
  },
  {
    id: 148,
    name: "Death's Embrace",
    location: "Arctic",
    rarity: 4,
    type: "Plant",
    magimins: { a: 33, b: 33, c: 33, d: 0, e: 33 },
    basePrice: 196,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 149,
    name: "Mana Blaze",
    location: "Dragon Oasis",
    rarity: 4,
    type: "Mana",
    magimins: { a: 50, b: 40, c: 30, d: 20, e: 10 },
    basePrice: 234,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 1, aroma: 1, visual: 0, sound: 0 },
  },
];

const dragonOasis = [
  {
    id: 150,
    name: "Gold Dollop",
    location: "Dragon Oasis",
    rarity: 3,
    type: "Slime",
    magimins: { a: 33, b: 33, c: 33, d: 33, e: 0 },
    basePrice: 176,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 151,
    name: "Pandemonium Shroom",
    location: "Dragon Oasis",
    rarity: 1,
    type: "Fungus",
    magimins: { a: 66, b: 0, c: 0, d: 0, e: 0 },
    basePrice: 72,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 152,
    name: "Dagonbreath Blossom",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Flower",
    magimins: { a: 33, b: 0, c: 0, d: 11, e: 0 },
    basePrice: 76,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 153,
    name: "Dragonblood Tick",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Bug",
    magimins: { a: 132, b: 66, c: 0, d: 0, e: 0 },
    basePrice: 174,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 154,
    name: "Bedazzled Custard",
    location: "Dragon Oasis",
    rarity: 1,
    type: "Slime",
    magimins: { a: 0, b: 0, c: 44, d: 0, e: 22 },
    basePrice: 95,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 155,
    name: "Dragonfire Pearl",
    location: "Dragon Oasis",
    rarity: 3,
    type: "Gem",
    magimins: { a: 0, b: 0, c: 0, d: 44, e: 0 },
    basePrice: 76,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 156,
    name: "Dragon Pheromones",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Essence",
    magimins: { a: 0, b: 0, c: 0, d: 0, e: 88 },
    basePrice: 151,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 157,
    name: "Widowmaker Pepper",
    location: "Dragon Oasis",
    rarity: 1,
    type: "Plant",
    magimins: { a: 0, b: 44, c: 0, d: 44, e: 0 },
    basePrice: 126,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 158,
    name: "Dragon Tear",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Essence",
    magimins: { a: 0, b: 33, c: 33, d: 11, e: 0 },
    basePrice: 118,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 159,
    name: "Funeral Pyre Enoki",
    location: "Dragon Oasis",
    rarity: 4,
    type: "Fungus",
    magimins: { a: 88, b: 88, c: 44, d: 44, e: 0 },
    basePrice: 280,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: -1, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 160,
    name: "Amethyst Ore",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Ore",
    magimins: { a: 66, b: 66, c: 0, d: 0, e: 33 },
    basePrice: 206,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 161,
    name: "Basilisk's Cornea",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Flesh",
    magimins: { a: 0, b: 22, c: 0, d: 0, e: 0 },
    basePrice: 54,
    quinnQuantity: 4,
    traits: { taste: 1, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 62,
    name: "Amphitere's Shadow",
    location: "Dragon Oasis",
    rarity: 1,
    type: "Essence",
    magimins: { a: 44, b: 0, c: 44, d: 0, e: 0 },
    basePrice: 114,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 163,
    name: "Magma Beetle",
    location: "Dragon Oasis",
    rarity: 1,
    type: "Bug",
    magimins: { a: 0, b: 33, c: 33, d: 33, e: 0 },
    basePrice: 124,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 164,
    name: "Dragonegg Citrus",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Fruit",
    magimins: { a: 0, b: 22, c: 0, d: 0, e: 66 },
    basePrice: 124,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 165,
    name: "Dragon Dung",
    location: "Dragon Oasis",
    rarity: 2,
    type: "Essence",
    magimins: { a: 0, b: 0, c: 88, d: 44, e: 0 },
    basePrice: 173,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: -1, visual: 0, sound: 0 },
  },
];

const crater = [
  {
    id: 166,
    name: "Cosmic Quartz",
    location: "Crater",
    rarity: 2,
    type: "Gem",
    magimins: { a: 66, b: 33, c: 0, d: 66, e: 0 },
    basePrice: 204,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 167,
    name: "Space Nautilus's Shell",
    location: "Crater",
    rarity: 1,
    type: "Mineral",
    magimins: { a: 44, b: 44, c: 0, d: 0, e: 0 },
    basePrice: 102,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 168,
    name: "Xeno Noir",
    location: "Crater",
    rarity: 3,
    type: "Fruit",
    magimins: { a: 66, b: 0, c: 66, d: 33, e: 33 },
    basePrice: 236,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 169,
    name: "Spark of Mana",
    location: "Crater",
    rarity: 4,
    type: "Mana",
    magimins: { a: 33, b: 33, c: 33, d: 33, e: 33 },
    basePrice: 215,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 170,
    name: "Cosmic Cassava",
    location: "Crater",
    rarity: 1,
    type: "Plant",
    magimins: { a: 0, b: 66, c: 0, d: 0, e: 0 },
    basePrice: 82,
    quinnQuantity: 10,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 171,
    name: "Xenoplasm",
    location: "Crater",
    rarity: 3,
    type: "Essences",
    magimins: { a: 0, b: 55, c: 55, d: 22, e: 0 },
    basePrice: 166,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 1 },
  },
  {
    id: 172,
    name: "Elder Being's Tusk",
    location: "Crater",
    rarity: 2,
    type: "Bone",
    magimins: { a: 0, b: 66, c: 0, d: 0, e: 22 },
    basePrice: 114,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 173,
    name: "Rotfly Mutant",
    location: "Crater",
    rarity: 1,
    type: "Bug",
    magimins: { a: 0, b: 0, c: 44, d: 0, e: 0 },
    basePrice: 74,
    quinnQuantity: 10,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 174,
    name: "Nightmare Pomme",
    location: "Crater",
    rarity: 3,
    type: "Fruit",
    magimins: { a: 0, b: 33, c: 11, d: 0, e: 0 },
    basePrice: 72,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 1 },
  },
  {
    id: 175,
    name: "Body Snatcher's Sloughed Skin",
    location: "Crater",
    rarity: 3,
    type: "Flesh",
    magimins: { a: 0, b: 0, c: 0, d: 66, e: 22 },
    basePrice: 132,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 176,
    name: "Armored Pudding",
    location: "Crater",
    rarity: 1,
    type: "Slime",
    magimins: { a: 44, b: 0, c: 0, d: 44, e: 0 },
    basePrice: 115,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 177,
    name: "Stalking Mold",
    location: "Crater",
    rarity: 1,
    type: "Fungus",
    magimins: { a: 22, b: 0, c: 0, d: 0, e: 66 },
    basePrice: 123,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 178,
    name: "Inverted Bramble-Rose",
    location: "Crater",
    rarity: 2,
    type: "Flower",
    magimins: { a: 22, b: 0, c: 0, d: 0, e: 0 },
    basePrice: 46,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 179,
    name: "Barracuda Plant",
    location: "Crater",
    rarity: 1,
    type: "Plant",
    magimins: { a: 22, b: 0, c: 55, d: 0, e: 55 },
    basePrice: 172,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 180,
    name: "Guillotine Eel",
    location: "Crater",
    rarity: 1,
    type: "Fish",
    magimins: { a: 33, b: 33, c: 33, d: 0, e: 0 },
    basePrice: 126,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 181,
    name: "Liquid Metal Ore",
    location: "Crater",
    rarity: 1,
    type: "Ore",
    magimins: { a: 0, b: 44, c: 88, d: 0, e: 0 },
    basePrice: 162,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: -1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 182,
    name: "Slaughtermelon",
    location: "Crater",
    rarity: 1,
    type: "Fruit",
    magimins: { a: 0, b: 0, c: 0, d: 76, e: 0 },
    basePrice: 105,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 0 },
  },
];

const magicalWasteland = [
  {
    id: 183,
    name: "Platinum Slime",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Slime",
    magimins: { a: 42, b: 42, c: 42, d: 0, e: 0 },
    basePrice: 178,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 184,
    name: "Nuclear Shadow",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Essence",
    magimins: { a: 0, b: 70, c: 70, d: 28, e: 0 },
    basePrice: 228,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 185,
    name: "Witchbramble Vine",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Plant",
    magimins: { a: 42, b: 42, c: 42, d: 0, e: 42 },
    basePrice: 210,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 186,
    name: "Mass Grave Enoki",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Fungus",
    magimins: { a: 56, b: 112, c: 112, d: 56, e: 0 },
    basePrice: 386,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: -1, aroma: -1, visual: 0, sound: 0 },
  },
  {
    id: 187,
    name: "Orchid of the Witch Queen",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Flower",
    magimins: { a: 28, b: 70, c: 0, d: 70, e: 0 },
    basePrice: 248,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 188,
    name: "Underworld Pomegranate",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Fruit",
    magimins: { a: 28, b: 28, c: 28, d: 140, e: 0 },
    basePrice: 332,
    quinnQuantity: 1,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: -1, sound: 0 },
  },
  {
    id: 189,
    name: "Venous Witch-Trap",
    location: "Magical Wasteland",
    rarity: 2,
    type: "Plant",
    magimins: { a: 28, b: 0, c: 70, d: 0, e: 70 },
    basePrice: 214,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 190,
    name: "Blightroach",
    location: "Magical Wasteland",
    rarity: 1,
    type: "Bug",
    magimins: { a: 0, b: 42, c: 42, d: 42, e: 0 },
    basePrice: 185,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 191,
    name: "Lethal Injection Eel",
    location: "Magical Wasteland",
    rarity: 1,
    type: "Fish",
    magimins: { a: 42, b: 42, c: 42, d: 0, e: 0 },
    basePrice: 164,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 192,
    name: "Sinfandel",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Fruit",
    magimins: { a: 80, b: 0, c: 80, d: 80, e: 40 },
    basePrice: 362,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 193,
    name: "Lich's Femur",
    location: "Magical Wasteland",
    rarity: 2,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 70, d: 70, e: 28 },
    basePrice: 247,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 194,
    name: "Sorcerite",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Mineral",
    magimins: { a: 70, b: 70, c: 0, d: 28, e: 0 },
    basePrice: 232,
    quinnQuantity: 2,
    traits: { taste: -1, sensation: 0, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 195,
    name: "Arcane Truffle",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Fungus",
    magimins: { a: 0, b: 42, c: 42, d: 42, e: 42 },
    basePrice: 236,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 196,
    name: "Ectoplasm",
    location: "Magical Wasteland",
    rarity: 3,
    type: "Essence",
    magimins: { a: 0, b: 70, c: 70, d: 28, e: 0 },
    basePrice: 226,
    quinnQuantity: 2,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: -1, sound: 1 },
  },
  {
    id: 197,
    name: "Cyclops Skull",
    location: "Magical Wasteland",
    rarity: 1,
    type: "Bone",
    magimins: { a: 0, b: 0, c: 42, d: 42, e: 42 },
    basePrice: 200,
    quinnQuantity: 10,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 198,
    name: "Blackgold Ore",
    location: "Magical Wasteland",
    rarity: 2,
    type: "Ore",
    magimins: { a: 84, b: 84, c: 0, d: 0, e: 42 },
    basePrice: 256,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 199,
    name: "Arcane Quartz",
    location: "Magical Wasteland",
    rarity: 2,
    type: "Gem",
    magimins: { a: 84, b: 0, c: 0, d: 84, e: 42 },
    basePrice: 264,
    quinnQuantity: 4,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 0, sound: -1 },
  },
  {
    id: 200,
    name: "Hocus Locust",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Bug",
    magimins: { a: 28, b: 28, c: 140, d: 28, e: 0 },
    basePrice: 287,
    quinnQuantity: 1,
    traits: { taste: 1, sensation: -1, aroma: 0, visual: 0, sound: 0 },
  },
  {
    id: 201,
    name: "Dazzling Mana",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 42, b: 42, c: 42, d: 42, e: 42 },
    basePrice: 345,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 1, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 202,
    name: "Mana Maelstrom",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 98, b: 28, c: 28, d: 28, e: 28 },
    basePrice: 375,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 0, visual: 1, sound: 1 },
  },
  {
    id: 203,
    name: "Mana Vortex",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 28, b: 98, c: 28, d: 28, e: 28 },
    basePrice: 400,
    quinnQuantity: 1,
    traits: { taste: 1, sensation: 0, aroma: 0, visual: 0, sound: 1 },
  },
  {
    id: 204,
    name: "Mana Prism",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 28, b: 28, c: 98, d: 28, e: 28 },
    basePrice: 425,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 1, aroma: 0, visual: 1, sound: 0 },
  },
  {
    id: 205,
    name: "Mana Heart",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 28, b: 28, c: 28, d: 98, e: 28 },
    basePrice: 450,
    quinnQuantity: 1,
    traits: { taste: 1, sensation: 0, aroma: 1, visual: 0, sound: 0 },
  },
  {
    id: 206,
    name: "Mana Singularity",
    location: "Magical Wasteland",
    rarity: 4,
    type: "Mana",
    magimins: { a: 28, b: 28, c: 28, d: 28, e: 98 },
    basePrice: 475,
    quinnQuantity: 1,
    traits: { taste: 0, sensation: 0, aroma: 1, visual: 0, sound: 1 },
  },
];

// Concat all arrays together
let ingredients = [];

ingredients = ingredients.concat(
  enchantedForest,
  mushroomMire,
  boneWastes,
  stormPlains,
  oceanCoasts,
  shadowSteppe,
  sulfuricFalls,
  iceCraggs,
  crystallineForest,
  arctic,
  dragonOasis,
  crater,
  magicalWasteland,
);
